### ISSUE TITLE
1.21.1 Neoforge crash when trying to start up world

### ISSUE THREAD

**Issue by BugmanBugman** [pajicadvance/soaring-phantoms#2]
[https://gist.github.com/BugmanBugman/aeb16c2508e24cea921e633a1dace7b6.js"](https://gist.github.com/BugmanBugman/aeb16c2508e24cea921e633a1dace7b6)

**Comment by pajicadvance** [comment]
Thanks for the report, there does seem to be a problem with the mod on NeoForge 1.21.2 and above. Taking a look right now.

**Comment by pajicadvance** [comment]
Let me know if this version works: 
https://modrinth.com/mod/soaring-phantoms/version/7Yxhcyxl
https://www.curseforge.com/minecraft/mc-mods/soaring-phantoms/files/6018361
